### ISSUE TITLE
Owner: Be able to delete QR codes [US 09.0X.01]

### ISSUE THREAD

**Issue by mrcromero** [CMPUT301W22T16/QR-Go#13]
As an owner, I want to be able to delete QR codes which are bad or malicious so that the players in the game are not offended or discouraged to play when they see them

- [x] flag on DB
- [x] functions to delete id
- [x] flag things connected to it
- [x] create delete button

**Comment by w3ichen** [comment]
Not done yet

**Comment by mrcromero** [comment]
Delete button now added to the search activity. Search list and the database are both updated when the button is pressed
