### ISSUE TITLE
Player: See other player's profiles [US 01.0X.01]

### ISSUE THREAD

**Issue by fariskazmi** [CMPUT301W22T16/QR-Go#14]
As a player, I want to be able to see other player's profiles, which should contain unique usernames and contact information, so that I can interact with them.

- [x] needed data
- [x] show qrcodes
- [x] show contact

**Comment by w3ichen** [comment]
A few things missing, but has been started

**Comment by LandynPugh** [comment]
Username, player score, highest unique score, and total number of qr codes scanned are displayed on activity.
