### ISSUE TITLE
Owner: Be able to delete players [US 09.0X.01]

### ISSUE THREAD

**Issue by mrcromero** [CMPUT301W22T16/QR-Go#15]
As an owner, I want to be able to have access to created profiles and delete undesirable ones so that I can moderate over the game's player base

- [x] flag on DB
- [x] function to delete id
- [x] flag things connected to it
- [x] create delete button

**Comment by w3ichen** [comment]
Not done yet

**Comment by mrcromero** [comment]
Delete button now added to the search activity. Search list and the database are both updated when the button is pressed
