### ISSUE TITLE
Player: Be able to decline geolocation recording

### ISSUE THREAD

**Issue by mrcromero** [CMPUT301W22T16/QR-Go#18]
When scanning a code, make geolocation recording optional

**Comment by w3ichen** [comment]
Done, geolocation can be tracked and declined using a checkbox.
The way that it's implemented, it will always attempt to always get user location on activity `onCreate`.
The user can click the location checkbox as many time as they want and nothing will happen.

Only when they hit **Save**, do we see if the checkbox is enabled or not.
If checked, do nothing, location is always stored
If unchecked, set the location to`null`
