### ISSUE TITLE
Player: Record optional photo when adding QR Codes [US 02.0X.01]

### ISSUE THREAD

**Issue by fariskazmi** [CMPUT301W22T16/QR-Go#19]
As a player, I want to have a choice of recording a photo of the object I took a QR Code from when adding a QR Code so that I can share where I found it

- [x] add to db Darius
- [x] activity
- [x] photo to db

**Comment by w3ichen** [comment]
Added button to take photo and is able to get the captured photo
TODO: save photo to database

**Comment by w3ichen** [comment]
Still waiting on database code. Front end is done
