### ISSUE TITLE
Player: Add comments on QR Codes [US 02.0X.01]

### ISSUE THREAD

**Issue by fariskazmi** [CMPUT301W22T16/QR-Go#20]
As a player, I would like to be able to add a comment to a QR Code I'm currently scanning or a QR Code I've scanned in the past so that I can interact and converse with other players

- [x] add comment to DB Darius
- [x] add comment on activity

**Comment by w3ichen** [comment]
Finished the database querying but is missing the button. Almost done

**Comment by w3ichen** [comment]
Still working. Not adding the comments yet - still need to implement that.
Back end from Darius is finished
