### ISSUE TITLE
Player: See a map of of nearby QR codes [US 06.01.01]

### ISSUE THREAD

**Issue by mrcromero** [CMPUT301W22T16/QR-Go#21]
As a player, I want to be able to view a map which shows the geo-locations of all nearby QR codes scanned by other players so that I know where to scan new QR-codes and gain more points

- [x] markers
- [x] location of player
- [x] QR info pop-up when tapping marker 
- [ ] algorithm to run nearby

**Comment by w3ichen** [comment]
Work in progress. Will have pins on map, but still need to implement the clicking of the map pins

**Comment by w3ichen** [comment]
Algorithm to get nearby qr codes is not done yet. Can look at Marco's code from search to see how to get nearby qr codes
