### ISSUE TITLE
Player: Browse QR Codes other players have scanned [US 02.0X.01]

### ISSUE THREAD

**Issue by fariskazmi** [CMPUT301W22T16/QR-Go#23]
As a player, I want to be able to look at any QR Codes any other plays have scanned so that we can compare our collection and determine who has been the better QR-hunter

**Comment by w3ichen** [comment]
Right now it does fetch the users from database. 
Still need to display the username and the pictures

**Comment by w3ichen** [comment]
Should ask TA about whether it is finished or not. Unsure about the "compare"
