### ISSUE TITLE
Player: be able to search for nearby QR codes by geo-location [US 05.0X.01]

### ISSUE THREAD

**Issue by mrcromero** [CMPUT301W22T16/QR-Go#24]
As a player, I want to be able to search for nearby QR-code using a geo-location so that I know where I can find new QR-codes to scan and gain more points

**Comment by w3ichen** [comment]
@fariskazmi will help with geo location

**Comment by mrcromero** [comment]
Based on my discussion with the prof, I think this is just the map + the QR list sorted by proximity, so I believe this is finished and no actual _searching_ needs to be done
