### ISSUE TITLE
Player: I want to see which players have previously scanned the QR Code I just scanned [US 02.0X.01]

### ISSUE THREAD

**Issue by fariskazmi** [CMPUT301W22T16/QR-Go#25]
As a player, I want to see other players that have scanned the same QR code so that I can determine the uniqueness of any code I've scanned as well as interact with other players.

**Comment by w3ichen** [comment]
Can show in activity but the database interfacing is not done

**Comment by w3ichen** [comment]
Right now it does fetch the users from database.
Still need to display the username and the pictures
