### ISSUE TITLE
Player: See game-wide high scores of all players [US 07.0X.01]

### ISSUE THREAD

**Issue by mrcromero** [CMPUT301W22T16/QR-Go#3]
As a player, I want to be able to see game-wide high scores for all players in the following categories:

- [x] Highest scoring QR codes
- [x] Highest sum of QR codes
- [x] Most QR codes
- [x] Highest scoring QR codes in a region

So that I can see how the best players are performing.

**Comment by mrcromero** [comment]
Ranking in region will not be implemented by the half-way point. Consider [GeoQueries](https://firebase.google.com/docs/firestore/solutions/geoqueries) during implementation

**Comment by w3ichen** [comment]
Almost done. Just working on the region stuff - just need to fix a bug

**Comment by mrcromero** [comment]
Bug fixed, region border currently set at 10km
