### ISSUE TITLE
Player: Profile should be created with unique username and contact information

### ISSUE THREAD

**Issue by fariskazmi** [CMPUT301W22T16/QR-Go#30]
As a player, I want a profile with a unique username and my contact information so that I can identify myself from other players

**Comment by w3ichen** [comment]
Almost done.
Generate username for user is done by Marco.
Faris is working on the Settings page activity

**Comment by fariskazmi** [comment]
Done. Username and email can be seen on player info page. Username and email can be set and edited from account page.
