### ISSUE TITLE
REVISION Proj 2: Convert Figma Mockups to Android Studio Activites

### ISSUE THREAD

**Issue by fariskazmi** [CMPUT301W22T16/QR-Go#33]
We want to convert 

https://www.figma.com/file/p4YQpmAkAw2VkmGpXoKw7v/QR-GO-UI-Final-Draft?node-id=0%3A1

- [x] PlayerStatsActivity 
- [x] QRCodeActivity
- [x] MapActivity
- [x] MapQRCodeFrag
- [x] SearchActivity
- [x] ListQRActivity
- [x] ScanActivity
- [x] PlayerSettingsActivity

**Comment by LandynPugh** [comment]
I can take Player settings and score pages

**Comment by mrcromero** [comment]
I can do PlayerStatsActivity and QRCodeActivity
