### ISSUE TITLE
Create Basic Classes

### ISSUE THREAD

**Issue by DarFang** [CMPUT301W22T16/QR-Go#35]
We want to make the classes

- [x]  QR code and User Marco, Weichen, Faris
- [x]  Geo Location Landyn
- [x]  Comment Matthew
- [x]  Photo Darius

**Comment by w3ichen** [comment]
We're just focusing on the java object classes for right now and leave the activities until later

**Comment by w3ichen** [comment]
@w3ichen 

- [ ] QR code classes
- [ ] Hashing algorithm

@mrcromero 

- [ ] User classes

@fariskazmi 

- [ ] Do the `ValidatePassword` method in the LoginQRCode. Maybe have database store with username and password. Check password matches the one in the database. Need to securely generate new qr code
