### ISSUE TITLE
REVISION Proj 2: Editing CRC cards

### ISSUE THREAD

**Issue by DarFang** [CMPUT301W22T16/QR-Go#37]
We want to update our CRC based on proj 2 feedback

**Comment by matthewzita** [comment]
[https://echeung.me/crcmaker/?share=W3sibmFtZSI6Ikhhc2giLCJzdXBlcmNsYXNzZXMiOiIiLCJzdWJjbGFzc2VzIjoiIiwidHlwZSI6MSwicmVzcG9uc2liaWxpdGllcyI6WyJSZXByZXNlbnRzIGEgaGFzaCIsIkNvbnRhaW5lZCBieSBhIFFSQ29kZSJdLCJjb2xsYWJvcmF0b3JzIjpbIlFSQ29kZSJdfSx7Im5hbWUiOiJRUkNvZGUiLCJzdXBlcmNsYXNzZXMiOiIiLCJzdWJjbGFzc2VzIjoiTG9naW5RUkNvZGUsIFN0YXR1c1FSQ29kZSwgR2FtZVFSQ29kZSIsInR5cGUiOjEsInJlc3BvbnNpYmlsaXRpZXMiOlsiUmVwcmVzZW50cyBhIFFSQ29kZSIsIkNvbnRhaW5zIGEgaGFzaCBjb2RlIiwiIl0sImNvbGxhYm9yYXRvcnMiOlsiSGFzaCIsIiJdfSx7Im5hbWUiOiJMb2dpblFSQ29kZSIsInN1cGVyY2xhc3NlcyI6IlFSQ29kZSIsInN1YmNsYXNzZXMiOiIiLCJ0eXBlIjoxLCJyZXNwb25zaWJpbGl0aWVzIjpbIlJlcHJlc2VudCBhIFFSQ29kZSB1c2VkIGZvciBsb2dnaW5nIGluIiwiQ29udGFpbmVkIGJ5IGEgVXNlciIsIlVzZWQgYnkgTG9naW5JbmZvQWN0aXZpdHkiXSwiY29sbGFib3JhdG9ycyI6WyJRUkNvZGUiLCJVc2VyIiwiTG9naW5JbmZvQWN0aXZpdHkiXX0seyJuYW1lIjoiU3RhdHVzUVJDb2RlIiwic3VwZXJjbGFzc2VzIjoiUVJDb2RlIiwic3ViY2xhc3NlcyI6IiIsInR5cGUiOjEsInJlc3BvbnNpYmlsaXRpZXMiOlsiUmVwcmVzZW50IGEgUVJDb2RlIGZvciBzaG93aW5nIHVzZXIgZGF0YSIsIkNvbnRhaW5lZCBieSBhIFVzZXIiXSwiY29sbGFib3JhdG9ycyI6WyJRUkNvZGUiLCJVc2VyIl19LHsibmFtZSI6IkdhbWVRUkNvZGUiLCJzdXBlcmNsYXNzZXMiOiJRUkNvZGUiLCJzdWJjbGFzc2VzIjoiIiwidHlwZSI6MSwicmVzcG9uc2liaWxpdGllcyI6WyJSZXByZXNlbnRzIGEgUVJDb2RlIHRoYXQgY2FuIGJlIHNjb3JlZCIsIktub3dzIHVzZXJzIHRoYXQgc2Nhbm5lZCBpdHNlbGYiLCJDb250YWluZWQgaW4gU2VhcmNoQWN0aXZpdHkiLCJDb250YWluZWQgaW4gUGxheWVySW5mb0FjdGl2aXR5IiwiQ29udGFpbmVkIGluIFFSSW5mb0FjdGl2aXR5IiwiR2V0cyBpdHMgb3duIHNjb3JlIl0sImNvbGxhYm9yYXRvcnMiOlsiUVJDb2RlIiwiU2VhcmNoQWN0aXZpdHkiLCJQbGF5ZXJJbmZvQWN0aXZpdHkiLCJRUkluZm9BY3Rpdml0eSJdfV0=](Here) is the link to the CRC Maker
