### ISSUE TITLE
Player: See all QR codes I have added [US 01.02.01]

### ISSUE THREAD

**Issue by fariskazmi** [CMPUT301W22T16/QR-Go#4]
As a player, I want to see all of the QR codes I have added to my account in the past so that I can keep inventory of all my collected QR-codes

- [x] query 
- [x] info page is not ( add check if its own player)

**Comment by w3ichen** [comment]
Not done yet. Need to implement the list on the UI. 
Changed assignee from Faris to Landyn

**Comment by w3ichen** [comment]
Can re-use code from list of qr codes shown in search activity. @LandynPugh contact Marco to find the code for list of qr codes

**Comment by w3ichen** [comment]
Almost done
