### ISSUE TITLE
Player: Remove QR Codes [US 01.0X.01]

### ISSUE THREAD

**Issue by fariskazmi** [CMPUT301W22T16/QR-Go#5]
As a player, I want to be able to remove any previous QR codes I have added to my account so that I can remove any that I don't like.

- [x] remove from db Darius
- [x] activity

**Comment by w3ichen** [comment]
Not started

**Comment by w3ichen** [comment]
Need to add option to the activity. Backend is done, frontend is not done. Should be fairly easy to do

**Comment by LandynPugh** [comment]
Users can delete their own QR codes on activity, but it does not immediately update the highest/lowest qr code headers.
