### ISSUE TITLE
Player: See my highest or lowest QR Code Scores [US 01.0X.01]

### ISSUE THREAD

**Issue by fariskazmi** [CMPUT301W22T16/QR-Go#7]
All QR Codes have different scores. As a player, I want to see which ones are the highest scoring or lowest scoring so that I can keep track of them and compare them with other players

**Comment by w3ichen** [comment]
Landyn will look into it.
Has not been started yet.

**Comment by fariskazmi** [comment]
User can see what is the highest/lowest score they have but can't see which QR code its associated with
